name: ci
on:
  push:
    branches:
      - $default-branch
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: [ '2.7' ]
    name: Ruby ${{ matrix.ruby }} tests
    steps:
      - uses: actions/checkout@v2

      - name: Setup git
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "Test"
          git config --global init.defaultBranch master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rake test
